modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/ProgrammerLP/TrainUtilitiesMod/issues"
license = "AGPL v3"
displayURL="https://modrinth.com/mod/create-trainutilities/"

[[mods]]
modId = "trainutilities"
version = "${version}"
displayName = "Create: TrainUtilities"
authors = "Adeptstack"
description = '''
Mod that adds custom sliding doors with sounds and station blocks, and also building blocks for stations and trains.
'''
logoFile = "mod_icon.png"

[[dependencies.trainutilities]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.trainutilities]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,]"
ordering="NONE"
side="BOTH"